package uk.gov.esos.api.authorization.regulator.domain;

public enum RegulatorPermissionGroup {

    MANAGE_USERS_AND_CONTACTS,
    MANAGE_PARTICIPANT_USERS,
    ASSIGN_REASSIGN_TASKS,

    REVIEW_ORGANISATION_ACCOUNT,
    RETURN_NOC,
    MANAGE_VERIFIED_ORGANISATION_ACCOUNTS,

    ACCOUNT_CLOSURE,

    RETURN_ACTION_PLAN,

    RETURN_PROGRESS_UPDATE_1,

    RETURN_PROGRESS_UPDATE_2
}
