/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionPlanP3 } from './actionPlanP3';

export interface ActionPlanP3ApplicationSubmitRequestTaskPayloadAllOf {
  actionPlanP3?: ActionPlanP3;
  actionPlanSectionsCompleted?: { [key: string]: string };
  actionPlanAttachments?: { [key: string]: string };
}
