/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Assets } from './assets';
import { CertificateDetails } from './certificateDetails';
import { CertificatesDetails } from './certificatesDetails';
import { EnergyConsumptionPotentialReduction } from './energyConsumptionPotentialReduction';
import { EnergySavingsCategoriesPotentialReduction } from './energySavingsCategoriesPotentialReduction';
import { TotalEnergyConsumptionReduction } from './totalEnergyConsumptionReduction';

export interface AlternativeComplianceRoutes {
  totalEnergyConsumptionReduction?: TotalEnergyConsumptionReduction;
  energyConsumptionReduction?: EnergyConsumptionPotentialReduction;
  energyConsumptionReductionCategories?: EnergySavingsCategoriesPotentialReduction;
  assets?: Assets;
  iso50001CertificateDetails?: CertificateDetails;
  decCertificatesDetails?: CertificatesDetails;
  gdaCertificatesDetails?: CertificatesDetails;
}
