/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyAudit } from './energyAudit';

export interface ComplianceRoute {
  estimatedCalculationTypes: Array<
    | 'TOTAL_OR_SIGNIFICANT_ENERGY_CONSUMPTION'
    | 'CONVERSION_OF_TOTAL_OR_SIGNIFICANT_ENERGY_CONSUMPTION'
    | 'AMOUNT_OF_TOTAL_OR_SIGNIFICANT_ENERGY_CONSUMPTION'
    | 'ENERGY_CONSUMPTION_OVER_TWELVE_MONTHS'
    | 'NONE_OF_THE_ABOVE'
  >;
  areTwelveMonthsVerifiableDataUsed?: boolean;
  twelveMonthsVerifiableDataUsedReason?: string;
  areEstimationMethodsRecorded: 'YES' | 'NO' | 'SKIP_QUESTION';
  energyConsumptionProfilingUsed?: 'YES' | 'NO' | 'NOT_APPLICABLE';
  areEnergyConsumptionProfilingMethodsRecorded?: 'YES' | 'NO' | 'SKIP_QUESTION';
  isEnergyConsumptionProfilingNotUsedRecorded?: 'YES' | 'NO' | 'SKIP_QUESTION';
  energyAudits?: Array<EnergyAudit>;
  partsProhibitedFromDisclosingExist: boolean;
  partsProhibitedFromDisclosing?: string;
  partsProhibitedFromDisclosingReason?: string;
}
