/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TotalEnergySavingsExpected } from './totalEnergySavingsExpected';

export interface EnergyEfficiencyMeasure {
  measureName: string;
  isEnergySavingsOpportunityReportedInAudit: boolean;
  measureScheme?: Array<
    | 'CLIMATE_CHANGE_AGREEMENTS_CCA'
    | 'STREAMLINED_ENERGY_AND_CARBON_REPORTING_SECR'
    | 'UK_EMISSIONS_TRADING_SCHEME_ETS'
    | 'UN_RACE_TO_ZERO'
    | 'SCIENCE_BASED_TARGETS_INITIATIVE_SBTI'
    | 'CARBON_REDUCTION_PLANS'
    | 'OTHER'
  >;
  otherMeasureSchemeName?: string;
  totalEnergySavingsExpected?: TotalEnergySavingsExpected;
  implementationDateForMeasure: string;
  energySavingsEstimateCalculatedType:
    | 'ENERGY_AUDIT'
    | 'ALTERNATIVE_COMPLIANCE_METHOD'
    | 'OTHER_REASONABLE_ESTIMATION_METHOD';
  estimationMethodDescription?: string;
  measureContext?: string;
}
