/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The verification token
 */
export interface InvitationTokenDTO {
  token: string;
  type:
    | 'USER_REGISTRATION'
    | 'OPERATOR_INVITATION'
    | 'REGULATOR_INVITATION'
    | 'VERIFIER_INVITATION'
    | 'CHANGE_2FA'
    | 'GET_FILE'
    | 'RESET_PASSWORD';
}
