/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NocP3 } from './nocP3';

export interface NocP3SearchResultsInfoDto {
  id?: string;
  organisationName?: string;
  registrationNumber?: string;
  location?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  noc?: NocP3;
  status?: 'AWAITING_APPROVAL' | 'LIVE' | 'DENIED' | 'CLOSED';
}
