/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NocP3SearchResultsInfoDto } from './nocP3SearchResultsInfoDto';

export interface NotificationOfCompliancesP3MiReportResult {
  reportType:
    | 'LIST_OF_ACCOUNTS_USERS_CONTACTS'
    | 'COMPLETED_WORK'
    | 'REGULATOR_OUTSTANDING_REQUEST_TASKS'
    | 'LIST_OF_ACCOUNTS_ASSIGNED_REGULATOR_SITE_CONTACTS'
    | 'LIST_OF_VERIFICATION_BODY_USERS'
    | 'NOC_SUBMITTED_DATA_P3'
    | 'CUSTOM'
    | 'ACTION_PLAN_SUBMITTED_DATA_P3'
    | 'PROGRESS_UPDATE_1_SUBMITTED_DATA_P3'
    | 'PROGRESS_UPDATE_2_SUBMITTED_DATA_P3';
  results?: { [key: string]: NocP3SearchResultsInfoDto };
  total: number;
}
