/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MiReportParams } from './miReportParams';

export interface OutstandingRegulatorRequestTasksMiReportParams extends MiReportParams {
  requestTaskTypes?: Array<
    | 'ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SUBMIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_WAIT_FOR_EDIT'
    | 'ACTION_PLAN_P3_APPLICATION_SUBMIT'
    | 'ACCOUNT_CLOSURE_SUBMIT'
    | 'PROGRESS_UPDATE_1_P3_APPLICATION_SUBMIT'
    | 'PROGRESS_UPDATE_2_P3_APPLICATION_SUBMIT'
  >;
  userIds?: Array<string>;
}
