/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate1P3AddedMeasure } from './progressUpdate1P3AddedMeasure';
import { ProgressUpdate1P3UpdatedMeasurePayload } from './progressUpdate1P3UpdatedMeasurePayload';

export interface ProgressUpdate1P3MeasuresUpdatePayload {
  progressUpdate1P3Measures?: Array<ProgressUpdate1P3UpdatedMeasurePayload>;
  progressUpdate1P3AddedMeasure?: Array<ProgressUpdate1P3AddedMeasure>;
}
