/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProgressUpdate1P3AddedMeasure {
  measureName: string;
  measureScheme?: Array<
    | 'CLIMATE_CHANGE_AGREEMENTS_CCA'
    | 'STREAMLINED_ENERGY_AND_CARBON_REPORTING_SECR'
    | 'UK_EMISSIONS_TRADING_SCHEME_ETS'
    | 'UN_RACE_TO_ZERO'
    | 'SCIENCE_BASED_TARGETS_INITIATIVE_SBTI'
    | 'CARBON_REDUCTION_PLANS'
    | 'OTHER'
  >;
  otherMeasureSchemeName?: string;
  reductionEnergyConsumption2024To2025: number;
  reductionEnergyConsumption2023To2024?: number;
  estimationMethodType: 'ENERGY_AUDIT' | 'OTHER_METHOD' | 'NO_METHOD_USED';
  estimationMethodDescription?: string;
  measureContext?: string;
}
