/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupChange } from './groupChange';
import { ProgressUpdate1P3MeasuresUpdate } from './progressUpdate1P3MeasuresUpdate';

export interface ProgressUpdate1P3 {
  groupChange?: GroupChange;
  progressUpdate1P3MeasuresUpdate: ProgressUpdate1P3MeasuresUpdate;
  responsibleOfficerConfirmation?: Array<'ESOS_ACTION_PLAN_COMPLIANCE' | 'ESTIMATION_METHOD_DOCUMENTED'>;
}
