/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate2P3AddedMeasure } from './progressUpdate2P3AddedMeasure';
import { ProgressUpdate2P3UpdatedMeasurePayload } from './progressUpdate2P3UpdatedMeasurePayload';

export interface ProgressUpdate2P3MeasuresUpdatePayload {
  progressUpdate2P3Measures?: Array<ProgressUpdate2P3UpdatedMeasurePayload>;
  progressUpdate2P3AddedMeasure?: Array<ProgressUpdate2P3AddedMeasure>;
}
