/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate1P3AddedMeasure } from './progressUpdate1P3AddedMeasure';
import { ProgressUpdate2P3EnergyEfficiencyMeasure } from './progressUpdate2P3EnergyEfficiencyMeasure';

export interface ProgressUpdate2P3UpdatedAddedMeasure {
  uuId: string;
  progressUpdate1P3AddedMeasure: ProgressUpdate1P3AddedMeasure;
  progressUpdate2P3EnergyEfficiencyMeasure: ProgressUpdate2P3EnergyEfficiencyMeasure;
}
