/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate2P3Payload } from './progressUpdate2P3Payload';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface ProgressUpdate2P3SaveApplicationRequestTaskActionPayload extends RequestTaskActionPayload {
  progressUpdate2P3?: ProgressUpdate2P3Payload;
  progressUpdate2P3SectionsCompleted?: { [key: string]: string };
}
