/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate1P3 } from './progressUpdate1P3';
import { RequestTaskPayload } from './requestTaskPayload';

export interface ProgressUpdate1P3ApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  isDisaggregateUndertaking?: boolean;
  progressUpdate1P3?: ProgressUpdate1P3;
  progressUpdate1P3SectionsCompleted?: { [key: string]: string };
  progressUpdate1P3Attachments?: { [key: string]: string };
}
