/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate1P3Payload } from './progressUpdate1P3Payload';

export interface ProgressUpdate1P3SaveApplicationRequestTaskActionPayloadAllOf {
  progressUpdate1P3?: ProgressUpdate1P3Payload;
  progressUpdate1P3SectionsCompleted?: { [key: string]: string };
}
