/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate2P3AddedMeasure } from './progressUpdate2P3AddedMeasure';
import { ProgressUpdate2P3UpdatedAddedMeasure } from './progressUpdate2P3UpdatedAddedMeasure';
import { ProgressUpdate2P3UpdatedMeasure } from './progressUpdate2P3UpdatedMeasure';

export interface ProgressUpdate2P3MeasuresUpdate {
  progressUpdate2P3Measures?: Array<ProgressUpdate2P3UpdatedMeasure>;
  progressUpdate2P3UpdatedAddedMeasures?: Array<ProgressUpdate2P3UpdatedAddedMeasure>;
  progressUpdate2P3AddedMeasure?: Array<ProgressUpdate2P3AddedMeasure>;
}
