/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate1P3EnergyEfficiencyMeasure } from './progressUpdate1P3EnergyEfficiencyMeasure';

export interface ProgressUpdate1P3UpdatedMeasurePayload {
  uuId: string;
  progressUpdate1P3EnergyEfficiencyMeasure: ProgressUpdate1P3EnergyEfficiencyMeasure;
}
