/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProgressUpdate1P3EnergyEfficiencyMeasure {
  measureIsImplemented?: boolean;
  measureImplementedByTheDateInActionPlan?: boolean;
  reductionEnergyConsumption2024To2025?: number;
  reductionEnergyConsumption2023To2024?: number;
  estimationMethodType?: 'ENERGY_AUDIT' | 'ACTION_PLAN_ESTIMATE' | 'OTHER_METHOD' | 'NO_METHOD_USED';
  estimationMethodDescription?: string;
  providedContext?: string;
  reportReduction2024To2025?: boolean;
  reportReduction2023To2024?: boolean;
}
