/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupChange } from './groupChange';
import { ProgressUpdate2P3MeasuresUpdatePayload } from './progressUpdate2P3MeasuresUpdatePayload';

export interface ProgressUpdate2P3Payload {
  groupChange?: GroupChange;
  progressUpdate2P3MeasuresUpdate?: ProgressUpdate2P3MeasuresUpdatePayload;
  responsibleOfficerConfirmation?: Array<'ESOS_ACTION_PLAN_COMPLIANCE' | 'ESTIMATION_METHOD_DOCUMENTED'>;
}
