/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressUpdate2P3 } from './progressUpdate2P3';

export interface ProgressUpdate2P3ApplicationRequestActionPayloadAllOf {
  isDisaggregateUndertaking?: boolean;
  progressUpdate2P3?: ProgressUpdate2P3;
  progressUpdate2Attachments?: { [key: string]: string };
}
