/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyEfficiencyMeasure } from './energyEfficiencyMeasure';
import { ProgressUpdate1P3EnergyEfficiencyMeasure } from './progressUpdate1P3EnergyEfficiencyMeasure';

export interface ProgressUpdate1P3UpdatedMeasure {
  uuId: string;
  measureImplType: 'MEASURE_IMPL_BEFORE_SUBMIT_ACTION_PLAN' | 'MEASURE_IMPL_AFTER_SUBMIT_ACTION_PLAN';
  actionPlanEnergyEfficiencyMeasure: EnergyEfficiencyMeasure;
  progressUpdate1P3EnergyEfficiencyMeasure: ProgressUpdate1P3EnergyEfficiencyMeasure;
}
