/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestInfoDTO {
  id?: string;
  type?:
    | 'ORGANISATION_ACCOUNT_OPENING'
    | 'NOTIFICATION_OF_COMPLIANCE_P3'
    | 'ACTION_PLAN_P3'
    | 'ACCOUNT_CLOSURE'
    | 'PROGRESS_UPDATE_1_P3'
    | 'PROGRESS_UPDATE_2_P3';
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  accountId?: number;
  requestMetadata?: RequestMetadata;
  paymentCompleted?: boolean;
  paymentAmount?: string;
}
