/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountClosureSaveApplicationRequestTaskActionPayload } from './accountClosureSaveApplicationRequestTaskActionPayload';
import { ActionPlanP3SaveApplicationRequestTaskActionPayload } from './actionPlanP3SaveApplicationRequestTaskActionPayload';
import { NotificationOfComplianceP3SaveApplicationRequestTaskActionPayload } from './notificationOfComplianceP3SaveApplicationRequestTaskActionPayload';
import { OrganisationAccountOpeningAmendApplicationRequestTaskActionPayload } from './organisationAccountOpeningAmendApplicationRequestTaskActionPayload';
import { OrganisationAccountOpeningSubmitDecisionRequestTaskActionPayload } from './organisationAccountOpeningSubmitDecisionRequestTaskActionPayload';
import { PaymentCancelRequestTaskActionPayload } from './paymentCancelRequestTaskActionPayload';
import { PaymentMarkAsReceivedRequestTaskActionPayload } from './paymentMarkAsReceivedRequestTaskActionPayload';
import { ProgressUpdate1P3SaveApplicationRequestTaskActionPayload } from './progressUpdate1P3SaveApplicationRequestTaskActionPayload';
import { ProgressUpdate2P3SaveApplicationRequestTaskActionPayload } from './progressUpdate2P3SaveApplicationRequestTaskActionPayload';
import { RdeForceDecisionRequestTaskActionPayload } from './rdeForceDecisionRequestTaskActionPayload';
import { RdeResponseSubmitRequestTaskActionPayload } from './rdeResponseSubmitRequestTaskActionPayload';
import { RdeSubmitRequestTaskActionPayload } from './rdeSubmitRequestTaskActionPayload';
import { RequestTaskActionEmptyPayload } from './requestTaskActionEmptyPayload';
import { RfiResponseSubmitRequestTaskActionPayload } from './rfiResponseSubmitRequestTaskActionPayload';
import { RfiSubmitRequestTaskActionPayload } from './rfiSubmitRequestTaskActionPayload';
import { SendToEditRequestTaskActionPayload } from './sendToEditRequestTaskActionPayload';

/**
 * The request task action body
 */
export interface RequestTaskActionProcessDTO {
  requestTaskActionType:
    | 'ORGANISATION_ACCOUNT_OPENING_AMEND_APPLICATION'
    | 'ORGANISATION_ACCOUNT_OPENING_SUBMIT_DECISION'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_SUBMIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_UPLOAD_ATTACHMENT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SEND_TO_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SUBMIT_APPLICATION'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_RETURN_TO_SUBMIT'
    | 'RFI_SUBMIT'
    | 'RFI_UPLOAD_ATTACHMENT'
    | 'RFI_RESPONSE_SUBMIT'
    | 'RFI_CANCEL'
    | 'RDE_SUBMIT'
    | 'RDE_RESPONSE_SUBMIT'
    | 'RDE_FORCE_DECISION'
    | 'RDE_UPLOAD_ATTACHMENT'
    | 'PAYMENT_MARK_AS_PAID'
    | 'PAYMENT_MARK_AS_RECEIVED'
    | 'PAYMENT_PAY_BY_CARD'
    | 'PAYMENT_CANCEL'
    | 'ACTION_PLAN_P3_SUBMIT_APPLICATION'
    | 'ACTION_PLAN_P3_SAVE_APPLICATION_SUBMIT'
    | 'ACTION_PLAN_CANCEL_APPLICATION'
    | 'ACCOUNT_CLOSURE_SUBMIT_APPLICATION'
    | 'ACCOUNT_CLOSURE_SAVE_APPLICATION_SUBMIT'
    | 'ACCOUNT_CLOSURE_CANCEL_APPLICATION'
    | 'PROGRESS_UPDATE_1_P3_SUBMIT_APPLICATION'
    | 'PROGRESS_UPDATE_1_P3_SAVE_APPLICATION_SUBMIT'
    | 'PROGRESS_UPDATE_1_CANCEL_APPLICATION'
    | 'PROGRESS_UPDATE_2_P3_SUBMIT_APPLICATION'
    | 'PROGRESS_UPDATE_2_P3_SAVE_APPLICATION_SUBMIT'
    | 'PROGRESS_UPDATE_2_CANCEL_APPLICATION';
  requestTaskActionPayload:
    | AccountClosureSaveApplicationRequestTaskActionPayload
    | ActionPlanP3SaveApplicationRequestTaskActionPayload
    | NotificationOfComplianceP3SaveApplicationRequestTaskActionPayload
    | OrganisationAccountOpeningAmendApplicationRequestTaskActionPayload
    | OrganisationAccountOpeningSubmitDecisionRequestTaskActionPayload
    | PaymentCancelRequestTaskActionPayload
    | PaymentMarkAsReceivedRequestTaskActionPayload
    | ProgressUpdate1P3SaveApplicationRequestTaskActionPayload
    | ProgressUpdate2P3SaveApplicationRequestTaskActionPayload
    | RdeForceDecisionRequestTaskActionPayload
    | RdeResponseSubmitRequestTaskActionPayload
    | RdeSubmitRequestTaskActionPayload
    | RequestTaskActionEmptyPayload
    | RfiResponseSubmitRequestTaskActionPayload
    | RfiSubmitRequestTaskActionPayload
    | SendToEditRequestTaskActionPayload;
  requestTaskId: number;
}
