package uk.gov.esos.api.authorization.core.domain;

public enum Permission {

    // Organisation Account Opening Application task
    PERM_ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW_VIEW_TASK,
    PERM_ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW_EXECUTE_TASK,

    // Notification Of Compliance Application task
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_SUBMIT_VIEW_TASK,
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_SUBMIT_EXECUTE_TASK,

    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_EDIT_VIEW_TASK,
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_EDIT_EXECUTE_TASK,

    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_RE_INITIATE_TASK,
    
    // Organisation Account Opening Archive task
    PERM_ORGANISATION_ACCOUNT_OPENING_ARCHIVE_VIEW_TASK,
    PERM_ORGANISATION_ACCOUNT_OPENING_ARCHIVE_EXECUTE_TASK,
    
    // Permissions for Task Assignment
    PERM_TASK_ASSIGNMENT,
    
    // User management
    PERM_ACCOUNT_USERS_EDIT,
    PERM_CA_USERS_EDIT,

    PERM_VB_ACCESS_ALL_ACCOUNTS,
    
    PERM_UPLOAD_VERIFIED_ORGANISATION_ACCOUNTS,
    PERM_ACCOUNT_NOTES_EDIT,
    PERM_ACCOUNT_DETAILS_EDIT,

    // Action plan task
    PERM_ACTION_PLAN_APPLICATION_SUBMIT_VIEW_TASK,
    PERM_ACTION_PLAN_APPLICATION_SUBMIT_EXECUTE_TASK,
    PERM_ACTION_PLAN_APPLICATION_RE_INITIATE_TASK,

    // Account closure
    PERM_ACCOUNT_CLOSURE_SUBMIT,

    // Progress update 1 task
    PERM_PROGRESS_UPDATE_1_APPLICATION_SUBMIT_VIEW_TASK,
    PERM_PROGRESS_UPDATE_1_APPLICATION_SUBMIT_EXECUTE_TASK,
    PERM_PROGRESS_UPDATE_1_APPLICATION_RE_INITIATE_TASK,

    // Progress update 2 task
    PERM_PROGRESS_UPDATE_2_APPLICATION_SUBMIT_VIEW_TASK,
    PERM_PROGRESS_UPDATE_2_APPLICATION_SUBMIT_EXECUTE_TASK,
    PERM_PROGRESS_UPDATE_2_APPLICATION_RE_INITIATE_TASK
}
