package uk.gov.esos.api.workflow.request.core.domain.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RequestCreateActionType {
    ORGANISATION_ACCOUNT_OPENING_SUBMIT_APPLICATION(RequestType.ORGANISATION_ACCOUNT_OPENING),
    NOTIFICATION_OF_COMPLIANCE_P3(RequestType.NOTIFICATION_OF_COMPLIANCE_P3),
    RE_INITIATE_NOTIFICATION_OF_COMPLIANCE_P3(RequestType.NOTIFICATION_OF_COMPLIANCE_P3),

    // ACTION PLAN
    ACTION_PLAN_P3(RequestType.ACTION_PLAN_P3),
    RE_INITIATE_ACTION_PLAN_P3(RequestType.ACTION_PLAN_P3),

    ACCOUNT_CLOSURE(RequestType.ACCOUNT_CLOSURE),

    // PROGRESS UPDATE 1
    PROGRESS_UPDATE_1_P3(RequestType.PROGRESS_UPDATE_1_P3),
    RE_INITIATE_PROGRESS_UPDATE_1_P3(RequestType.PROGRESS_UPDATE_1_P3),

    // PROGRESS UPDATE 2
    PROGRESS_UPDATE_2_P3(RequestType.PROGRESS_UPDATE_2_P3),
    RE_INITIATE_PROGRESS_UPDATE_2_P3(RequestType.PROGRESS_UPDATE_2_P3);

    private final RequestType type;
}
