package uk.gov.esos.api.workflow.request.core.domain.enumeration;

public enum RequestTaskActionPayloadType {

    ORGANISATION_ACCOUNT_OPENING_AMEND_APPLICATION_PAYLOAD,
    ORGANISATION_ACCOUNT_OPENING_SUBMIT_DECISION_PAYLOAD,

    NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_SUBMIT_PAYLOAD,
    NOTIFICATION_OF_COMPLIANCE_P3_SEND_TO_EDIT_PAYLOAD,
    NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_EDIT_PAYLOAD,

    RFI_SUBMIT_PAYLOAD,
    RFI_RESPONSE_SUBMIT_PAYLOAD,
    
    RDE_SUBMIT_PAYLOAD,
    RDE_RESPONSE_SUBMIT_PAYLOAD,
    RDE_FORCE_DECISION_PAYLOAD,
    
    PAYMENT_MARK_AS_RECEIVED_PAYLOAD,
    PAYMENT_CANCEL_PAYLOAD,

    ACTION_PLAN_P3_SAVE_APPLICATION_SUBMIT_PAYLOAD,

    ACCOUNT_CLOSURE_SAVE_APPLICATION_SUBMIT_PAYLOAD,

    PROGRESS_UPDATE_1_P3_SAVE_APPLICATION_SUBMIT_PAYLOAD,

    PROGRESS_UPDATE_2_P3_SAVE_APPLICATION_SUBMIT_PAYLOAD,


    EMPTY_PAYLOAD
}
