package uk.gov.esos.api.workflow.request.core.domain.enumeration;

public enum RequestCreateActionPayloadType {

    ORGANISATION_ACCOUNT_OPENING_SUBMIT_APPLICATION_PAYLOAD,
    REPORT_RELATED_REQUEST_CREATE_ACTION_PAYLOAD,
    EMPTY_PAYLOAD,
    PROGRESS_UPDATE_1_CREATE_ACTION_PAYLOAD,
    PROGRESS_UPDATE_2_CREATE_ACTION_PAYLOAD
}
