import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'esos-api';

export const cancelActionMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  ACCOUNT_CLOSURE_SUBMIT: 'ACCOUNT_CLOSURE_CANCEL_APPLICATION',
  ACTION_PLAN_P3_APPLICATION_SUBMIT: 'ACTION_PLAN_CANCEL_APPLICATION',
  PROGRESS_UPDATE_1_P3_APPLICATION_SUBMIT: 'PROGRESS_UPDATE_1_CANCEL_APPLICATION',
  PROGRESS_UPDATE_2_P3_APPLICATION_SUBMIT: 'PROGRESS_UPDATE_2_CANCEL_APPLICATION',
};
